[build]
  command = "CI=false npm install --legacy-peer-deps && CI=false npm run build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "18"

# Handle SPA routing (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 